require("plugins.theme")
require("plugins.fff")
require("plugins.nvim-notify")
require("plugins.fidget")
require("plugins.mini-surround")
require("plugins.mini-ai")
require("plugins.todo-comments")
require("plugins.smear")
require("plugins.cloak")
require("plugins.flash")
require("plugins.formatting")
require("plugins.trouble")

require("plugins.lsp")
require("plugins.treesitter")
require("plugins.blink")
require("plugins.copilot")
-- require("plugins.gitsigns")
-- require("plugins.lualine")
require("plugins.snacks")
